# To deploy:
# aws cloudformation deploy \
#   --template-file dryseq-stack.yml \
#   --stack-name dryseq-stack \
#   --capabilities CAPABILITY_NAMED_IAM \
#   --parameter-overrides \
#       KeyPairName=my-key \
#       DBMasterUserPassword=supersecret \
#   --profile personal

AWSTemplateFormatVersion: '2010-09-09'
Description: DrySeq Infra - Frontend, Uploads, EC2 backend, RDS DB

Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  DBMasterUserPassword:
    Description: Password for RDS master user
    Type: String
    NoEcho: true
    MinLength: 8

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: User your default VPC or a specific one

Resources:

  # === S3 Buckets ===

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dryseq-frontend
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dryseq-userdata

  # === IAM Role for EC2 ===

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dryseq-ec2-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  # === Parameter Groups ===

  DrySeqDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for DrySeq Postgres17 DB
      Family: postgres17
      Parameters:
        log_min_messages: error

  # === Security Groups ===

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP + SSH
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres from EC2
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EC2SecurityGroup

  # === RDS PostgreSQL ===

  DrySeqDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: dryseq
      Engine: postgres
      EngineVersion: "17.5"
      MasterUsername: dryseqadmin
      MasterUserPassword: !Ref DBMasterUserPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      DBParameterGroupName: !Ref DrySeqDBParameterGroup

  # === EC2 Instance ===

  DrySeqBackend:
    Type: AWS::EC2::Instance
    Metadata:
      UpdateMessage: "DrySeqBackend v0.0.1"
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !GetAtt EC2SecurityGroup.GroupId
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: ami-0263dd5562cf9d185 # Amazon Linux 2023 AMI (us-east-1)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # DrySeq deploy script
          set -euxo pipefail

          dnf update -y

          # Install Git, Python 3, and PostgreSQL client
          dnf install -y git nodejs python3 postgresql15
          npm install -g pm2

          cd /home/ec2-user

          rm -rf DrySeq
          git clone --branch main https://github.com/dgellerup/DrySeq.git
          cd DrySeq/backend

          echo "Current git commit:"
          git log -1

          # Write .env file with DB connection info
          echo "DATABASE_URL=postgresql://dryseqadmin:${DBMasterUserPassword}@${DrySeqDB.Endpoint.Address}:5432/dryseq" > .env

          # Install backend dependencies
          npm ci

          # Push schema to RDS
          npx prisma generate
          npx prisma db push

          echo "Prisma db push complete"

          # Start backend with PM2
          pm2 start server.js
          pm2 save

          # Set permissions
          chown -R ec2-user:ec2-user /home/ec2-user

Outputs:

  FrontendBucketURL:
    Description: URL to access the hosted React frontend
    Value: !Sub "http://${FrontendBucket}.s3-website-${AWS::Region}.amazonaws.com"

  EC2PublicIP:
    Description: IP address of the backend EC2 server
    Value: !GetAtt DrySeqBackend.PublicIp

  RDSHost:
    Description: RDS PostgreSQL host
    Value: !GetAtt DrySeqDB.Endpoint.Address
